import React from 'react';
import { cn } from '../../utils';

// Import curated set of ~100 commonly-used Lucide icons
import {
  // Navigation
  Home,
  Menu,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronDown,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUp,
  ChevronsDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  ArrowUpRight,
  ArrowDownLeft,
  CornerUpLeft,
  CornerUpRight,
  Move,
  ExternalLink,
  // Actions
  Plus,
  Minus,
  X,
  Check,
  Pencil,
  Trash,
  Trash2,
  Save,
  Copy,
  Clipboard,
  ClipboardCheck,
  ClipboardPaste,
  Scissors,
  Undo,
  Redo,
  RefreshCw,
  RotateCcw,
  RotateCw,
  // Files
  File,
  FileText,
  FilePlus,
  FileMinus,
  FileCheck,
  FileX,
  Folder,
  FolderOpen,
  FolderPlus,
  FolderMinus,
  Upload,
  Download,
  CloudOff,
  Image,
  Video,
  Music,
  Archive,
  // Documents
  Book,
  BookOpen,
  Building,
  Building2,
  // UI
  Search,
  Settings,
  Settings2,
  SlidersHorizontal,
  Filter,
  ArrowUpAZ,
  ArrowDownAZ,
  MoreHorizontal,
  MoreVertical,
  GripVertical,
  GripHorizontal,
  Maximize,
  Minimize,
  Maximize2,
  Minimize2,
  Expand,
  Shrink,
  Eye,
  EyeOff,
  Lock,
  Unlock,
  Key,
  Link,
  Link2,
  Unlink,
  // Users
  User,
  Users,
  UserPlus,
  UserMinus,
  UserCheck,
  UserX,
  LogIn,
  LogOut,
  // Status
  CheckCircle,
  CheckCircle2,
  XCircle,
  AlertCircle,
  Info,
  AlertTriangle,
  Loader,
  Loader2,
  Circle,
  CircleDot,
  Ban,
  // Communication
  Mail,
  MailOpen,
  Send,
  Inbox,
  MessageCircle,
  MessageSquare,
  Bell,
  BellOff,
  Phone,
  PhoneCall,
  PhoneOff,
  // Media
  Play,
  Pause,
  StopCircle,
  SkipBack,
  SkipForward,
  FastForward,
  Rewind,
  Volume,
  Volume1,
  Volume2,
  VolumeX,
  // Data
  BarChart,
  BarChart2,
  LineChart,
  PieChart,
  Activity,
  TrendingUp,
  TrendingDown,
  Database,
  Server,
  // Layout
  Layout,
  LayoutGrid,
  LayoutList,
  PanelLeft,
  PanelRight,
  PanelTop,
  PanelBottom,
  Columns,
  Rows,
  // Misc
  Star,
  Heart,
  ThumbsUp,
  ThumbsDown,
  Bookmark,
  Flag,
  Tag,
  Hash,
  AtSign,
  Calendar,
  Clock,
  Timer,
  AlarmClock,
  Map,
  MapPin,
  Navigation,
  Compass,
  Globe,
  Wifi,
  Bluetooth,
  Battery,
  Power,
  Zap,
  Sun,
  Moon,
  Cloud,
  Umbrella,
  Thermometer,
  Droplet,
  Wind,
  Code,
  Terminal,
  Github,
  Gitlab,
  Package,
  Box,
  ShoppingCart,
  ShoppingBag,
  CreditCard,
  DollarSign,
  Percent,
  Gift,
  Truck,
  Printer,
  Camera,
  Mic,
  Headphones,
  Monitor,
  Smartphone,
  Tablet,
  Laptop,
  Watch,
  Tv,
  Cpu,
  HardDrive,
  Shield,
  ShieldCheck,
  Award,
  Target,
  Crosshair,
  Layers,
  Square,
  Triangle,
  Hexagon,
  Octagon,
  HelpCircle,
  LifeBuoy,
  WifiOff,
  // Additional icons for docs & common use
  Rocket,
  Grid3x3,
  MousePointerClick,
  Route,
  Radio,
  Palette,
  Component,
  Type,
  TextCursorInput,
  Table,
  BarChart3,
  Wrench,
  Hammer,
  Puzzle,
  Paintbrush,
  HandMetal,
  CheckSquare,
  LayoutDashboard,
} from 'lucide-react';

import type { LucideIcon } from 'lucide-react';

// Map icon names to Lucide components
const iconMap: Record<string, LucideIcon> = {
  // Navigation
  'home': Home,
  'menu': Menu,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'chevron-down': ChevronDown,
  'chevrons-left': ChevronsLeft,
  'chevrons-right': ChevronsRight,
  'chevrons-up': ChevronsUp,
  'chevrons-down': ChevronsDown,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  'arrow-up-right': ArrowUpRight,
  'arrow-down-left': ArrowDownLeft,
  'corner-up-left': CornerUpLeft,
  'corner-up-right': CornerUpRight,
  'move': Move,
  'external-link': ExternalLink,
  // Actions
  'plus': Plus,
  'minus': Minus,
  'x': X,
  'check': Check,
  'edit': Pencil,
  'edit-2': Pencil,
  'edit-3': Pencil,
  'pencil': Pencil,
  'trash': Trash,
  'trash-2': Trash2,
  'save': Save,
  'copy': Copy,
  'clipboard': Clipboard,
  'clipboard-check': ClipboardCheck,
  'paste': ClipboardPaste,
  'cut': Scissors,
  'scissors': Scissors,
  'undo': Undo,
  'redo': Redo,
  'refresh-cw': RefreshCw,
  'refresh': RefreshCw,
  'rotate-ccw': RotateCcw,
  'rotate-cw': RotateCw,
  // Files
  'file': File,
  'file-text': FileText,
  'file-plus': FilePlus,
  'file-minus': FileMinus,
  'file-check': FileCheck,
  'file-x': FileX,
  'folder': Folder,
  'folder-open': FolderOpen,
  'folder-plus': FolderPlus,
  'folder-minus': FolderMinus,
  'upload': Upload,
  'download': Download,
  'cloud-off': CloudOff,
  'image': Image,
  'video': Video,
  'music': Music,
  'archive': Archive,
  // Documents & Buildings
  'book': Book,
  'book-open': BookOpen,
  'building': Building,
  'building-2': Building2,
  // UI
  'search': Search,
  'settings': Settings,
  'settings-2': Settings2,
  'sliders': SlidersHorizontal,
  'sliders-horizontal': SlidersHorizontal,
  'filter': Filter,
  'sort-asc': ArrowUpAZ,
  'sort-desc': ArrowDownAZ,
  'more-horizontal': MoreHorizontal,
  'more-vertical': MoreVertical,
  'ellipsis': MoreHorizontal,
  'grip-vertical': GripVertical,
  'grip-horizontal': GripHorizontal,
  'maximize': Maximize,
  'minimize': Minimize,
  'maximize-2': Maximize2,
  'minimize-2': Minimize2,
  'expand': Expand,
  'shrink': Shrink,
  'eye': Eye,
  'eye-off': EyeOff,
  'lock': Lock,
  'unlock': Unlock,
  'key': Key,
  'link': Link,
  'link-2': Link2,
  'unlink': Unlink,
  // Users
  'user': User,
  'users': Users,
  'user-plus': UserPlus,
  'user-minus': UserMinus,
  'user-check': UserCheck,
  'user-x': UserX,
  'log-in': LogIn,
  'log-out': LogOut,
  'login': LogIn,
  'logout': LogOut,
  // Status
  'check-circle': CheckCircle,
  'check-circle-2': CheckCircle2,
  'x-circle': XCircle,
  'alert-circle': AlertCircle,
  'info': Info,
  'alert-triangle': AlertTriangle,
  'warning': AlertTriangle,
  'loader': Loader,
  'loader-2': Loader2,
  'spinner': Loader2,
  'circle': Circle,
  'circle-dot': CircleDot,
  'ban': Ban,
  // Communication
  'mail': Mail,
  'email': Mail,
  'mail-open': MailOpen,
  'send': Send,
  'inbox': Inbox,
  'message-circle': MessageCircle,
  'message-square': MessageSquare,
  'chat': MessageCircle,
  'bell': Bell,
  'bell-off': BellOff,
  'notification': Bell,
  'phone': Phone,
  'phone-call': PhoneCall,
  'phone-off': PhoneOff,
  // Media
  'play': Play,
  'pause': Pause,
  'stop-circle': StopCircle,
  'stop': StopCircle,
  'skip-back': SkipBack,
  'skip-forward': SkipForward,
  'fast-forward': FastForward,
  'rewind': Rewind,
  'volume': Volume,
  'volume-1': Volume1,
  'volume-2': Volume2,
  'volume-x': VolumeX,
  'mute': VolumeX,
  // Data
  'bar-chart': BarChart,
  'bar-chart-2': BarChart2,
  'chart': BarChart2,
  'line-chart': LineChart,
  'pie-chart': PieChart,
  'activity': Activity,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  'database': Database,
  'server': Server,
  // Layout
  'layout': Layout,
  'layout-grid': LayoutGrid,
  'grid': LayoutGrid,
  'layout-list': LayoutList,
  'list': LayoutList,
  'sidebar': PanelLeft,
  'panel-left': PanelLeft,
  'panel-right': PanelRight,
  'panel-top': PanelTop,
  'panel-bottom': PanelBottom,
  'columns': Columns,
  'rows': Rows,
  // Misc
  'star': Star,
  'heart': Heart,
  'like': Heart,
  'thumbs-up': ThumbsUp,
  'thumbs-down': ThumbsDown,
  'bookmark': Bookmark,
  'flag': Flag,
  'tag': Tag,
  'hash': Hash,
  'hashtag': Hash,
  'at-sign': AtSign,
  'at': AtSign,
  'calendar': Calendar,
  'clock': Clock,
  'time': Clock,
  'timer': Timer,
  'alarm-clock': AlarmClock,
  'alarm': AlarmClock,
  'map': Map,
  'map-pin': MapPin,
  'location': MapPin,
  'pin': MapPin,
  'navigation': Navigation,
  'compass': Compass,
  'globe': Globe,
  'world': Globe,
  'wifi': Wifi,
  'wifi-off': WifiOff,
  'bluetooth': Bluetooth,
  'battery': Battery,
  'power': Power,
  'zap': Zap,
  'lightning': Zap,
  'sun': Sun,
  'moon': Moon,
  'cloud': Cloud,
  'umbrella': Umbrella,
  'thermometer': Thermometer,
  'droplet': Droplet,
  'water': Droplet,
  'wind': Wind,
  'code': Code,
  'terminal': Terminal,
  'console': Terminal,
  'github': Github,
  'gitlab': Gitlab,
  'package': Package,
  'box': Box,
  'shopping-cart': ShoppingCart,
  'cart': ShoppingCart,
  'shopping-bag': ShoppingBag,
  'bag': ShoppingBag,
  'credit-card': CreditCard,
  'card': CreditCard,
  'dollar-sign': DollarSign,
  'dollar': DollarSign,
  'money': DollarSign,
  'percent': Percent,
  'gift': Gift,
  'truck': Truck,
  'delivery': Truck,
  'printer': Printer,
  'print': Printer,
  'camera': Camera,
  'mic': Mic,
  'microphone': Mic,
  'headphones': Headphones,
  'audio': Headphones,
  'monitor': Monitor,
  'desktop': Monitor,
  'smartphone': Smartphone,
  'mobile': Smartphone,
  'tablet': Tablet,
  'laptop': Laptop,
  'watch': Watch,
  'tv': Tv,
  'television': Tv,
  'cpu': Cpu,
  'processor': Cpu,
  'hard-drive': HardDrive,
  'hdd': HardDrive,
  'shield': Shield,
  'shield-check': ShieldCheck,
  'security': Shield,
  'award': Award,
  'trophy': Award,
  'target': Target,
  'crosshair': Crosshair,
  'layers': Layers,
  'square': Square,
  'triangle': Triangle,
  'hexagon': Hexagon,
  'octagon': Octagon,
  'help-circle': HelpCircle,
  'help': HelpCircle,
  'life-buoy': LifeBuoy,
  'support': LifeBuoy,
  // Additional icons for docs & common use
  'rocket': Rocket,
  'grid-3x3': Grid3x3,
  'mouse-pointer-click': MousePointerClick,
  'route': Route,
  'radio': Radio,
  'palette': Palette,
  'component': Component,
  'type': Type,
  'text-cursor-input': TextCursorInput,
  'table': Table,
  'bar-chart-3': BarChart3,
  'wrench': Wrench,
  'hammer': Hammer,
  'puzzle': Puzzle,
  'paintbrush': Paintbrush,
  'hand-metal': HandMetal,
  'check-square': CheckSquare,
  'layout-dashboard': LayoutDashboard,
};

export interface IconProps {
  name: string;
  size?: number;
  color?: string;
  strokeWidth?: number;
  className?: string;
  'data-refast-id'?: string;
}

/**
 * Icon component that renders Lucide icons by name.
 * 
 * Falls back to rendering the name as text if the icon is not found,
 * which allows for backward compatibility with emoji icons.
 */
export function Icon({
  name,
  size = 16,
  color,
  strokeWidth = 2,
  className,
  'data-refast-id': dataRefastId,
}: IconProps): React.ReactElement {
  const LucideIcon = iconMap[name.toLowerCase()];

  if (LucideIcon) {
    return (
      <LucideIcon
        size={size}
        color={color}
        strokeWidth={strokeWidth}
        className={cn('shrink-0', className)}
        data-refast-id={dataRefastId}
        aria-hidden="true"
      />
    );
  }

  // Fallback: render the name as text (supports emojis and text)
  return (
    <span
      className={cn('inline-flex shrink-0 items-center justify-center', className)}
      style={{ 
        width: size, 
        height: size,
        fontSize: size * 0.875,
        lineHeight: 1,
      }}
      data-refast-id={dataRefastId}
      aria-hidden="true"
    >
      {name}
    </span>
  );
}

/**
 * Check if an icon name exists in the icon map.
 */
export function hasIcon(name: string): boolean {
  return name.toLowerCase() in iconMap;
}

/**
 * Get list of all available icon names.
 */
export function getIconNames(): string[] {
  return Object.keys(iconMap);
}
